export const floatingTabBarStyle = {
  position: 'absolute',
  bottom: 14,
  left: 16,
  right: 16,
  borderRadius: 20,
  height: 66,
  backgroundColor: '#ffffff',
  borderTopWidth: 0,
  shadowColor: '#0f172a',
  shadowOpacity: 0.18,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 8 },
  elevation: 8,
  paddingBottom: 8,
  paddingTop: 8,
};
